conteudo/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
urlpatterns = patterns('conteudo.views',

        url(r'^novo-codigo/$', 'novo_codigo', name='novo_codigo'),
        url(r'^cancelar-codigo-promocional/(?P<id>\d+)$', 'cancelar_codigo_promocional', name='cancelar_codigo_promocional'),
        url(r'^editar-codigo-promocional/(?P<id>\d+)$', 'editar_codigo_promocional', name='editar_codigo_promocional'),
        url(r'^nova-noticia/$', 'nova_noticia', name='nova_noticia'),
        url(r'^cancelar-noticia/(?P<id>\d+)$', 'cancelar_noticia', name='cancelar_noticia'),
        url(r'^editar-noticia/(?P<id>\d+)$', 'editar_noticia', name='editar_noticia'),
        url(r'^n/(?P<id>\d+)$', 'detalhes_noticia', name='detalhes_noticia'),
        url(r'^mapa/$', 'mapa', name='mapa'),
        url(r'^denuncia/$', 'denuncia', name='denuncia'),

)

front/urls.py
# coding=utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('front.views',
                       url(r'^$', 'index', name='index'),
                       url(r'^clientes/$', 'clientes', name='clientes'),
                       url(r'^categorias/$', 'categorias', name='categorias'),
                       url(r'^bairros/$', 'bairros', name='bairros'),
                       url(r'^codigos-promocionais/$', 'codigos_promocionais', name='codigos_promocionais'),
                       url(r'^noticias/$', 'noticias', name='noticias'),
                       url(r'^msg-padrao/$', 'msg_padrao', name='msg_padrao'),

)

keepsms/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

                       url(r'^gestao/', include(admin.site.urls)),
                       url('', include('cadastro.urls', namespace='cadastro')),
                       url('', include('localizacao.urls', namespace='localizacao')),
                       url('', include('front.urls', namespace='front')),
                       url('', include('mensagem.urls', namespace='mensagem')),
                       url('', include('conteudo.urls', namespace='conteudo')),
                       url('', include('financeiro.urls', namespace='financeiro')),
                       url('', include('autenticacao.urls', namespace='autenticacao')),
                       url(r'^retorno/pagseguro/', include('pagseguro.urls')),

)

if settings.DEBUG:
    urlpatterns = patterns('',
                           url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                               {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                           url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
                               {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
    ) + urlpatterns

front/models.py
# -*- coding: utf-8 -*-

front/forms.py
# -*- coding: utf-8 -*-

front/views.py
# coding=utf-8
from django.shortcuts import render
from cadastro.models import Usuario, Bairro, Categoria, ORIGEM_CHOICES
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from libs.util import list_paginator
from mensagem.models import Mensagem, MensagemPadrao, StatusMensagem
from conteudo.models import CodigoPromocional, New
from mensagem.api import consulta_status_detalhado
from front.decorators import verifica_termos_uso

@login_required(login_url='/login/')
@verifica_termos_uso()
def index(request):

    # print consulta_status_detalhado('')

    kwargs = {}
    args = []

    categoria       = request.GET.get('categoria', False)
    bairro          = request.GET.get('bairro', False)
    nome            = request.GET.get('nome_celular', False)
    mensagem_padrao = request.GET.get('mensagem_padrao', False)
    status          = request.GET.get('status', False)
    codigo          = request.GET.get('codigo', False)
    noticia         = request.GET.get('noticia', False)
    id_usuario         = request.GET.get('id_usuario', False)

    if categoria: kwargs['categoria'] = categoria
    if codigo: kwargs['codigo_promocional'] = codigo
    if id_usuario: kwargs['usuario'] = id_usuario

    if bairro: kwargs['bairro'] = bairro
    if mensagem_padrao: kwargs['mensagem_padrao'] = mensagem_padrao
    if status: kwargs['status'] = status
    if noticia: kwargs['noticia'] = noticia

    if nome: args = [Q(texto__icontains=nome) | Q(usuario__nome__contains=nome) | Q(usuario__celular__contains=nome)]

    opts_filtros = [200, 999, 5000, 5001, 5002, 000, 10, 13, 100, 110, 111, 120, 133, 134, 150, 160, 161, 171, 190, 01]

    mensagens = Mensagem.objects.filter(*args, **kwargs)

    for mensagem in mensagens:
        mensagem.atualiza_status()

    dados = {
        'titulo': u'SMS - (%s) ' % Mensagem.objects.filter(*args, **kwargs).count(),
        'mensagens': list_paginator(request, mensagens, 20),
        'bairros': Bairro.objects.all(),
        'categorias': Categoria.objects.all(),
        'mensagens_padrao': MensagemPadrao.objects.all(),
        'noticias': New.objects.all(),
        'codigo_promocionais': CodigoPromocional.objects.all(),
        'status': StatusMensagem.objects.filter(codigo__in=opts_filtros),
        'origens': dict(ORIGEM_CHOICES),
        'menu': "menu_mensagens",
    }

    return render(request, 'mensagens/mensagens.html', dados)

@login_required(login_url='/login/')
def msg_padrao(request):
    return render(request, 'mensagens-padrao/mensagens-padrao.html', {'titulo': u'SMS Padrão', 'menu': "menu_mensagem", 'mensagens': list_paginator(request, MensagemPadrao.objects.all(), 50),})

@login_required(login_url='/login/')
def noticias(request):
    return render(request, 'noticias/noticias.html', {'titulo': u'Noticias', 'menu': "menu_conteudo", 'noticias': list_paginator(request, New.objects.all(), 50),})

@login_required(login_url='/login/')
def codigos_promocionais(request):

    kwargs = {}
    args = []

    codigo = request.GET.get('codigo', False)
    if codigo:args = [Q(codigo__icontains=request.GET.get('codigo', False))]

    dados = {
        'titulo': u'Códigos Promocionais',
        'menu': "menu_conteudo",
        'codigos': list_paginator(request, CodigoPromocional.objects.filter(*args, **kwargs), 100),
    }

    return render(request, 'codigos/codigos.html', dados)

@login_required(login_url='/login/')
def clientes(request):

    kwargs = {}
    args = []

    categoria = request.GET.get('categoria', False)
    bairro = request.GET.get('bairro', False)
    nome = request.GET.get('nome_celular', False)
    origem = request.GET.get('origem', False)

    if categoria: kwargs['categoria'] = categoria
    if bairro: kwargs['bairro'] = bairro
    if origem: kwargs['origem'] = origem
    
    if nome: args = [Q(nome__icontains=nome) | Q(celular__contains=nome)]

    dados = {
        'titulo': u'Clientes (%s)' % Usuario.objects.all().count(),
        'clientes': list_paginator(request, Usuario.objects.filter(*args, **kwargs).filter(numero_invalido=False), 50),
        'bairros': Bairro.objects.all(),
        'categorias': Categoria.objects.all(),
        'origens': dict(ORIGEM_CHOICES),
        'menu': "menu_clientes",
    }

    return render(request, 'clientes/clientes.html', dados)

@login_required(login_url='/login/')
def categorias(request):
    return render(request, 'categorias/categorias.html', {'titulo': u'Categorias', 'categorias': Categoria.objects.all(), 'menu': "menu_clientes",})

@login_required(login_url='/login/')
def bairros(request):
    return render(request, 'bairros/bairros.html',{'titulo': u'Bairros', 'bairros': Bairro.objects.all(), 'menu': "menu_clientes",})

front/templates/noticias/detalhes.html
{% extends "front.html" %}
{% load front_extras %}
{% load widget_tweaks %}
{% load thumbnail %}
{% block menu_left %}

    <nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold" style="color: #fff;">{{ configuracao.nome }}</strong></span>
                </div>
                <div class="logo-element">
                    Keep
                </div>
            </li>

        </ul>

    </div>
</nav>

{% endblock %}

{% block bar_top %}{% endblock %}
{% block info_creditos %}{% endblock %}
{% block zopin %}{% endblock %}

{% block rodape %}
    <div class="footer" style="clear: both">
        <div class="pull-right">
            <strong>{{ configuracao.nome }}</strong>
        </div>
        <div>
            <a href="#" class="enviar_denuncia"><strong style="color:red"> <span class="fa fa-exclamation-circle fa-1x"> </span> Denunciar Abuso</strong></a>
            <span class="load_envio"></span>
        </div>
    </div>
{% endblock %}


{% block meta_tags %}

    <meta content="{{ noticia.title }}" name="description"/>
    <meta content="{{ configuracao.nome }}" name="generator"/>

    <meta content="article" property="og:type"/>
    <meta content="pt_BR" property="og:locale"/>

    <meta content="{{ noticia.url }}" property="og:url"/>

    <meta content="{{ configuracao.nome }}" property="og:site_name"/>

{#    <meta content="http://patoshoje.com.br/media/cache/f4/89/f48957f69360b3f6f114899bef620404.jpg" property="og:image"/>#}

    <meta content="{{ noticia.title }}" property="og:description"/>
    <meta content="{{ configuracao.nome }}" property="og:title"/>
    <meta content="1489049374719115" property="fb:page_id"/>
{#    <meta content="http://patoshoje.com.br/static/imgs/logofb.png" itemprop="image"/>#}
    <link href="http://www.site.com.br/" rel="canonical"/>
{% endblock %}

{% block content %}
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55569334142b5be2" async="async"></script>

    <div class="row">

        <div class="wrapper wrapper-content animated fadeInUp">
            <div class="ibox">
                <div class="ibox-content">
                    <div class="texto_noticia">
                        {{ noticia.texto|safe }}
                        <input id="noticia_id" value="{{ noticia.pk }}" type="hidden" />

                    </div>
                    {% if imagens %}
                        <br>
                        <h3>Clique na imagem para ampliar:</h3>
                        <div class="popup-gallery">
                        {% for image in imagens %}
                            {% thumbnail image.image "100x80" crop="center" as im %}

                                {% thumbnail image.image "500x500" crop="center" as imbig %}
                                    <a href="{{ imbig.url }}">
                                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="imagem_album" />
                                    </a>
                                {% endthumbnail %}

                            {% endthumbnail %}
                        {% endfor %}
                        </div>

                    {% endif %}

                    <div style="padding: 20px 0">
                        <a href="tel:{{ configuracao.telefone }}" class="btn btn-white btn-bitbucket">
                            <i class="fa fa-phone"></i> {{ configuracao.telefone }}
                        </a>
                        <a href="tel:{{ configuracao.celular }}" class="btn btn-white btn-bitbucket">
                            <i class="fa fa-mobile-phone"></i> {{ configuracao.celular }}
                        </a>

                        <a href="whatsapp://" class="btn btn-white btn-bitbucket">
                            <i class="fa fa-mobile-phone"></i> Whatsapp
                        </a>

                        {% if configuracao.site %}
                            <a href="http://{{ configuracao.site }}" class="btn btn-white btn-bitbucket">
                                <i class="fa fa-link"></i> {{ configuracao.site }}
                            </a>
                        {% endif %}

                        <a href="{% url "conteudo:mapa" %}" class="btn btn-white btn-bitbucket">
                            <i class="fa fa-link"></i> Localização
                        </a>
                         <a href="mailto:{{ configuracao.email }}" class="btn btn-white btn-bitbucket">
                            <i class="fa fa-envelope"></i> {{ configuracao.email }}
                        </a>
                    </div>

                    <!-- Go to www.addthis.com/dashboard to customize your tools -->
                    <div class="addthis_sharing_toolbox"></div>
                    <a href="whatsapp://{{ noticia.url }}?text={{ noticia.title }}" data-action="share/whatsapp/share">
                        <img src="{{ STATIC_URL }}img/whatsapp.png" />
                    </a>


                </div>
            </div>
        </div>


    </div>

{% endblock %}

front/templates/noticias/mapa.html
{% extends "front.html" %}
{% load front_extras %}
{% load widget_tweaks %}
{% load thumbnail %}
{% block menu_left %}

    <nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold" style="color: #fff;">{{ configuracao.nome }}</strong></span>
                </div>
                <div class="logo-element">
                    Keep
                </div>
            </li>

        </ul>

    </div>
</nav>

{% endblock %}

{% block bar_top %}{% endblock %}
{% block info_creditos %}{% endblock %}
{% block zopin %}{% endblock %}

{% block rodape %}
    <div class="footer" style="clear: both">
        <div class="pull-right">
            <strong>{{ configuracao.nome }}</strong>
        </div>
        <div>
            <a href="#" class="enviar_denuncia"><strong style="color:red"> <span class="fa fa-exclamation-circle fa-1x"> </span> Denunciar Abuso</strong></a>
            <span class="load_envio"></span>
        </div>
    </div>
{% endblock %}


{% block content %}
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55569334142b5be2" async="async"></script>

    <div class="row">

        <div class="wrapper wrapper-content animated fadeInUp">
            <div class="ibox">
                <div class="ibox-content">

                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15125.586292661685!2d-46.523482999999985!3d-18.60122425!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94aef548ff003cd9%3A0xb1eafe24688b9384!2s+{{ configuracao.endereco }}!5e0!3m2!1spt-BR!2sbr!4v1430659798870" width="100%" height="350" frameborder="0" style="border:0"></iframe>

                   <div style="padding: 20px 0">
                        <a href="tel:{{ configuracao.telefone }}" class="btn btn-white btn-bitbucket">
                            <i class="fa fa-phone"></i> {{ configuracao.telefone }}
                        </a>
                        <a href="tel:{{ configuracao.celular }}" class="btn btn-white btn-bitbucket">
                            <i class="fa fa-mobile-phone"></i> {{ configuracao.celular }}
                        </a>

                        <a href="whatsapp://" class="btn btn-white btn-bitbucket">
                            <i class="fa fa-mobile-phone"></i> Whatsapp
                        </a>

                        {% if configuracao.site %}
                            <a href="http://{{ configuracao.site }}" class="btn btn-white btn-bitbucket">
                                <i class="fa fa-link"></i> {{ configuracao.site }}
                            </a>
                        {% endif %}

                        <a href="mailto:{{ configuracao.email }}" class="btn btn-white btn-bitbucket">
                            <i class="fa fa-envelope"></i> {{ configuracao.email }}
                        </a>


                    </div>

                    <!-- Go to www.addthis.com/dashboard to customize your tools -->
                    <div class="addthis_sharing_toolbox"></div>
                    <a href="whatsapp://{{ noticia.url }}?text={{ noticia.title }}" data-action="share/whatsapp/share">
                        <img src="{{ STATIC_URL }}img/whatsapp.png" />
                    </a>


                </div>
            </div>
        </div>


    </div>

{% endblock %}

front/templates/noticias/noticias.html
{% extends "front.html" %}
{% load front_extras %}
{% load bootstrap_pagination %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
                <div class="ibox-content">

                    <div class="text-right">
                        <a href="{% url "conteudo:nova_noticia" %}" class="btn btn-success"> Adicionar Notícia </a>
                    </div>

                    <div class="table-responsive margem_table_lista">

                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Título</th>
                                <th>Ver Notícia</th>
                                <th>Link</th>
                                <th>Data</th>
                                <th>Cliques</th>

                            </tr>
                            </thead>
                            <tbody>

                            {% for noticia in noticias %}
                                <tr>
                                    <td><a href="{% url "conteudo:editar_noticia" noticia.pk %}" title="Clique para editar">{{ noticia }}</a></td>
                                    <td><a href="{% url "conteudo:detalhes_noticia" noticia.pk %}">+ detalhes </a></td>
                                    <td>{{ noticia.url }}</td>
                                    <td>{{ noticia.data_pt }}</td>
                                    <td>{{ noticia.access_number|default:"0" }}</td>

                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>

                </div>

            </div>
        </div>
    </div>

    </div>

{% endblock %}

front/templates/noticias/novo.html
{% extends "front.html" %}
{% load front_extras %}
{% load widget_tweaks %}

{% block content %}
    <script src="{{ STATIC_URL }}ckeditor/ckeditor.js"></script>
    <script src="{{ STATIC_URL }}ckeditor/config.js"></script>

    <style>
        #id_texto_count{
            display: none;
        }
    </style>



    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">

                <div class="ibox-content">

                    <div class="panel-body col-lg-12">

                        <div class="pull-right">
                            <a href="{% url "front:noticias" %}" class="label"> <span class="fa fa-bars fa-1x"> </span> Voltar para lista </a>
                        </div>

                        {% if form.non_field_errors %}
                            <div class="alert alert-danger">{{ form.non_field_errors }}</div>
                        {% endif %}
                        {% if noticia %}
                            <form action="{% url "conteudo:editar_noticia" noticia.pk %}" method="post" role="form" enctype="multipart/form-data">
                        {% else %}
                            <form action="{% url "conteudo:nova_noticia" %}" method="post" role="form" enctype="multipart/form-data">
                        {% endif %}

                            {% csrf_token %}
                            <div class="form-group">

                                <label>Descrição:</label> <span class="marca_texto_vermelho">(Obrigatório)</span>
                                {{ form.title.errors }}
                                {{ form.title|add_class:"form-control"|attr:"required:true"|attr:"placeholder:Esse título será enviado pelo SMS" }}
                            </div>

                             <div class="form-group alert alert-warning">
                                    Exemplo:  "Confira nossas novidades clicando no link:"
                            </div>

                            <div class="form-group">
                                 <label>Texto:</label> <span class="marca_texto_vermelho">(Obrigatório)</span>
                                {{ form.texto.errors }}
                                {{ form.texto|add_class:"form-control ckeditor"|attr:"rows:3" }}
                            </div>
                             <div class="form-group" id="form_set">


                                            {% for form in formset %}
                                                {% for hidden in form.hidden_fields %}
                                                    {{ hidden }}
                                                {% endfor %}
                                            {% endfor %}
                                            <table id="id_forms_table" class="table table-striped" border="0" cellpadding="5" cellspacing="5">

                                                <thead>
                                                    <tr>
                                                       <th>Imagens Extra</th>
                                                        <th>Remover</th>
                                                    </tr>
                                                </thead>
                                                <tbody>

                                                {% for fs in formset.forms %}
                                                    <tr id="{{ fs.prefix }}-row" class="dynamic-form {% if forloop.counter == 1 %} primeiro_item_form {% endif %}">
                                                        <td>
                                                            {{ fs.image }}
                                                            {{ fs.image.errors }}

                                                        </td>

                                                        <td style="text-align: center" align="center">
                                                            {% if fs.instance.pk %}
                                                                {{ fs.DELETE }}
                                                                Apagar
                                                            {% else %}
                                                                <a id="remove-{{ fs.prefix }}-row" href="javascript:void(0)" class="delete-row">remover</a>
                                                            {% endif %}


                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>

                                            </table>
                                            <a href="javascript:void(0)" class="add-row btn btn-w-m btn-default">+ Imagem</a>

                                        </div>
                            <div class="form-group">
                                <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit" name="salvar"
                                        value="1" style="margin-left: 15px"><strong>Salvar</strong></button>

                            </div>
                            {{ formset.management_form }}
                        </form>

                    </div>


                </div>
            </div>
        </div>
    </div>

{% endblock %}