cadastro/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
urlpatterns = patterns('cadastro.views',
        url(r'^detalhe-cliente/(?P<id>\d+)$', 'detalhes', name='detalhes'),
        url(r'^desabilitar-recebimento-campanha/(?P<id>\d+)$', 'desabilitar_recebimento_campanha', name='desabilitar_recebimento_campanha'),
        url(r'^editar-cliente/(?P<id>\d+)$', 'editar', name='editar'),
        url(r'^novo-cliente/$', 'novo', name='novo'),
        url(r'^importar-planilha/$', 'importar_planilha', name='importar_planilha'),
        url(r'^editar-categoria/(?P<id>\d+)$', 'editar_categoria', name='editar_categoria'),
        url(r'^novo-categoria/$', 'nova_categoria', name='nova_categoria'),
        url(r'^cancelar-categoria/(?P<id>\d+)$', 'cancelar_categoria', name='cancelar_categoria'),
        url(r'^numeros-invalidos/$', 'numeros_invalidos', name='numeros_invalidos'),
        url(r'^remover-numeros-invalidos/$', 'remover_numeros_invalidos', name='remover_numeros_invalidos'),
)

front/urls.py
# coding=utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('front.views',
                       url(r'^$', 'index', name='index'),
                       url(r'^clientes/$', 'clientes', name='clientes'),
                       url(r'^categorias/$', 'categorias', name='categorias'),
                       url(r'^bairros/$', 'bairros', name='bairros'),
                       url(r'^codigos-promocionais/$', 'codigos_promocionais', name='codigos_promocionais'),
                       url(r'^noticias/$', 'noticias', name='noticias'),
                       url(r'^msg-padrao/$', 'msg_padrao', name='msg_padrao'),

)

keepsms/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

                       url(r'^gestao/', include(admin.site.urls)),
                       url('', include('cadastro.urls', namespace='cadastro')),
                       url('', include('localizacao.urls', namespace='localizacao')),
                       url('', include('front.urls', namespace='front')),
                       url('', include('mensagem.urls', namespace='mensagem')),
                       url('', include('conteudo.urls', namespace='conteudo')),
                       url('', include('financeiro.urls', namespace='financeiro')),
                       url('', include('autenticacao.urls', namespace='autenticacao')),
                       url(r'^retorno/pagseguro/', include('pagseguro.urls')),

)

if settings.DEBUG:
    urlpatterns = patterns('',
                           url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                               {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                           url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
                               {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
    ) + urlpatterns

front/models.py
# -*- coding: utf-8 -*-

front/forms.py
# -*- coding: utf-8 -*-

front/views.py
# coding=utf-8
from django.shortcuts import render
from cadastro.models import Usuario, Bairro, Categoria, ORIGEM_CHOICES
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from libs.util import list_paginator
from mensagem.models import Mensagem, MensagemPadrao, StatusMensagem
from conteudo.models import CodigoPromocional, New
from mensagem.api import consulta_status_detalhado
from front.decorators import verifica_termos_uso

@login_required(login_url='/login/')
@verifica_termos_uso()
def index(request):

    # print consulta_status_detalhado('')

    kwargs = {}
    args = []

    categoria       = request.GET.get('categoria', False)
    bairro          = request.GET.get('bairro', False)
    nome            = request.GET.get('nome_celular', False)
    mensagem_padrao = request.GET.get('mensagem_padrao', False)
    status          = request.GET.get('status', False)
    codigo          = request.GET.get('codigo', False)
    noticia         = request.GET.get('noticia', False)
    id_usuario         = request.GET.get('id_usuario', False)

    if categoria: kwargs['categoria'] = categoria
    if codigo: kwargs['codigo_promocional'] = codigo
    if id_usuario: kwargs['usuario'] = id_usuario

    if bairro: kwargs['bairro'] = bairro
    if mensagem_padrao: kwargs['mensagem_padrao'] = mensagem_padrao
    if status: kwargs['status'] = status
    if noticia: kwargs['noticia'] = noticia

    if nome: args = [Q(texto__icontains=nome) | Q(usuario__nome__contains=nome) | Q(usuario__celular__contains=nome)]

    opts_filtros = [200, 999, 5000, 5001, 5002, 000, 10, 13, 100, 110, 111, 120, 133, 134, 150, 160, 161, 171, 190, 01]

    mensagens = Mensagem.objects.filter(*args, **kwargs)

    for mensagem in mensagens:
        mensagem.atualiza_status()

    dados = {
        'titulo': u'SMS - (%s) ' % Mensagem.objects.filter(*args, **kwargs).count(),
        'mensagens': list_paginator(request, mensagens, 20),
        'bairros': Bairro.objects.all(),
        'categorias': Categoria.objects.all(),
        'mensagens_padrao': MensagemPadrao.objects.all(),
        'noticias': New.objects.all(),
        'codigo_promocionais': CodigoPromocional.objects.all(),
        'status': StatusMensagem.objects.filter(codigo__in=opts_filtros),
        'origens': dict(ORIGEM_CHOICES),
        'menu': "menu_mensagens",
    }

    return render(request, 'mensagens/mensagens.html', dados)

@login_required(login_url='/login/')
def msg_padrao(request):
    return render(request, 'mensagens-padrao/mensagens-padrao.html', {'titulo': u'SMS Padrão', 'menu': "menu_mensagem", 'mensagens': list_paginator(request, MensagemPadrao.objects.all(), 50),})

@login_required(login_url='/login/')
def noticias(request):
    return render(request, 'noticias/noticias.html', {'titulo': u'Noticias', 'menu': "menu_conteudo", 'noticias': list_paginator(request, New.objects.all(), 50),})

@login_required(login_url='/login/')
def codigos_promocionais(request):

    kwargs = {}
    args = []

    codigo = request.GET.get('codigo', False)
    if codigo:args = [Q(codigo__icontains=request.GET.get('codigo', False))]

    dados = {
        'titulo': u'Códigos Promocionais',
        'menu': "menu_conteudo",
        'codigos': list_paginator(request, CodigoPromocional.objects.filter(*args, **kwargs), 100),
    }

    return render(request, 'codigos/codigos.html', dados)

@login_required(login_url='/login/')
def clientes(request):

    kwargs = {}
    args = []

    categoria = request.GET.get('categoria', False)
    bairro = request.GET.get('bairro', False)
    nome = request.GET.get('nome_celular', False)
    origem = request.GET.get('origem', False)

    if categoria: kwargs['categoria'] = categoria
    if bairro: kwargs['bairro'] = bairro
    if origem: kwargs['origem'] = origem
    
    if nome: args = [Q(nome__icontains=nome) | Q(celular__contains=nome)]

    dados = {
        'titulo': u'Clientes (%s)' % Usuario.objects.all().count(),
        'clientes': list_paginator(request, Usuario.objects.filter(*args, **kwargs).filter(numero_invalido=False), 50),
        'bairros': Bairro.objects.all(),
        'categorias': Categoria.objects.all(),
        'origens': dict(ORIGEM_CHOICES),
        'menu': "menu_clientes",
    }

    return render(request, 'clientes/clientes.html', dados)

@login_required(login_url='/login/')
def categorias(request):
    return render(request, 'categorias/categorias.html', {'titulo': u'Categorias', 'categorias': Categoria.objects.all(), 'menu': "menu_clientes",})

@login_required(login_url='/login/')
def bairros(request):
    return render(request, 'bairros/bairros.html',{'titulo': u'Bairros', 'bairros': Bairro.objects.all(), 'menu': "menu_clientes",})

front/templates/categorias/categorias.html
{% extends "front.html" %}
{% load front_extras %}
{% load bootstrap_pagination %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
                <div class="ibox-content">

                    <div class="text-right">
                        <a href="{% url "cadastro:nova_categoria" %}" class="btn btn-success"> Adicionar Categoria </a>
                    </div>

                    <div class="table-responsive margem_table_lista">

                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Total de Clientes</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for categoria in categorias %}
                                <tr>
                                    <td><a href="{% url "cadastro:editar_categoria" categoria.pk %}"
                                           title="Clique para editar">{{ categoria }}</a></td>
                                    <td>{{ categoria.total_clientes }}</td>

                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>

                </div>

                <script type="text/javascript">
                    google.load("visualization", "1", {packages: ["corechart"]});
                    google.setOnLoadCallback(drawChart);
                    function drawChart() {

                        var data = google.visualization.arrayToDataTable([
                            ['Task', 'Categorias'],
                            {% for categoria in categorias %}
                                ['{{ categoria.nome }}', {{ categoria.total_clientes }}],
                            {% endfor %}
                        ]);

                        var options = {
                            title: 'Clientes por Categoria'
                        };

                        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

                        chart.draw(data, options);
                    }
                </script>
                <div id="piechart" style="width: 100%; height: 500px;"></div>

            </div>
        </div>
    </div>

    </div>

{% endblock %}

front/templates/categorias/novo.html
{% extends "front.html" %}
{% load front_extras %}
{% load widget_tweaks %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">

                <div class="ibox-content">

                    <div class="panel-body col-lg-6">
                        <div class="pull-right">
                            <a href="{% url "front:categorias" %}" class="label"> <span class="fa fa-bars fa-1x"> </span> Voltar para lista </a>
                        </div>
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger">{{ form.non_field_errors }}</div>
                        {% endif %}

                        {% if categoria %}
                            <form action="{% url "cadastro:editar_categoria" categoria.pk %}" method="post" role="form">
                        {% else %}
                            <form action="{% url "cadastro:nova_categoria" %}" method="post" role="form">
                        {% endif %}


                            {% csrf_token %}
                            <div class="form-group">

                                <label>Nome:</label>
                                {{ form.nome.errors }}
                                {{ form.nome|add_class:"form-control"|attr:"required:true" }}
                            </div>

                            <div class="form-group">
                                <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit" name="salvar"
                                        value="1" style="margin-left: 15px"><strong>Salvar</strong></button>

                            </div>

                        </form>

                    </div>


                </div>
            </div>
        </div>
    </div>

{% endblock %}