cadastro/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
urlpatterns = patterns('cadastro.views',
        url(r'^detalhe-cliente/(?P<id>\d+)$', 'detalhes', name='detalhes'),
        url(r'^desabilitar-recebimento-campanha/(?P<id>\d+)$', 'desabilitar_recebimento_campanha', name='desabilitar_recebimento_campanha'),
        url(r'^editar-cliente/(?P<id>\d+)$', 'editar', name='editar'),
        url(r'^novo-cliente/$', 'novo', name='novo'),
        url(r'^importar-planilha/$', 'importar_planilha', name='importar_planilha'),
        url(r'^editar-categoria/(?P<id>\d+)$', 'editar_categoria', name='editar_categoria'),
        url(r'^novo-categoria/$', 'nova_categoria', name='nova_categoria'),
        url(r'^cancelar-categoria/(?P<id>\d+)$', 'cancelar_categoria', name='cancelar_categoria'),
        url(r'^numeros-invalidos/$', 'numeros_invalidos', name='numeros_invalidos'),
        url(r'^remover-numeros-invalidos/$', 'remover_numeros_invalidos', name='remover_numeros_invalidos'),
)

front/urls.py
# coding=utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('front.views',
                       url(r'^$', 'index', name='index'),
                       url(r'^clientes/$', 'clientes', name='clientes'),
                       url(r'^categorias/$', 'categorias', name='categorias'),
                       url(r'^bairros/$', 'bairros', name='bairros'),
                       url(r'^codigos-promocionais/$', 'codigos_promocionais', name='codigos_promocionais'),
                       url(r'^noticias/$', 'noticias', name='noticias'),
                       url(r'^msg-padrao/$', 'msg_padrao', name='msg_padrao'),

)

keepsms/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

                       url(r'^gestao/', include(admin.site.urls)),
                       url('', include('cadastro.urls', namespace='cadastro')),
                       url('', include('localizacao.urls', namespace='localizacao')),
                       url('', include('front.urls', namespace='front')),
                       url('', include('mensagem.urls', namespace='mensagem')),
                       url('', include('conteudo.urls', namespace='conteudo')),
                       url('', include('financeiro.urls', namespace='financeiro')),
                       url('', include('autenticacao.urls', namespace='autenticacao')),
                       url(r'^retorno/pagseguro/', include('pagseguro.urls')),

)

if settings.DEBUG:
    urlpatterns = patterns('',
                           url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                               {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                           url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
                               {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
    ) + urlpatterns

cadastro/models.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.utils.safestring import mark_safe
from libs.util import ModelDefault
import csv
import re
import os
from localizacao.models import Bairro

ORIGEM_FORMULARIO = 'f'
ORIGEM_PLANILHA = 'p'
ORIGEM_TABLET = 't'
ORIGEM_INDICACAO = 'i'

ORIGEM_CHOICES = (
            (ORIGEM_FORMULARIO, _(u'Formulário')),
            (ORIGEM_PLANILHA, _(u'Planilha')),
            (ORIGEM_TABLET, _(u'Tablet')),
            (ORIGEM_INDICACAO, _(u'Indicação')),
)

class Categoria(ModelDefault):
    class Meta:
        verbose_name = _(u'Categoria')
        verbose_name_plural = _(u'Categorias')
        ordering = ['nome']

    nome                = models.CharField(verbose_name=_(u'Nome'), max_length=150)
    def __unicode__(self): return u'%s' % self.nome

    def total_clientes(self): return Usuario.objects.filter(categoria=self.pk).count()


class Operadora(ModelDefault):
    class Meta:
        verbose_name = _(u'Operadora')
        verbose_name_plural = _(u'Operadoras')
        ordering = ['nome']

    nome                = models.CharField(verbose_name=_(u'Nome'), max_length=150)
    def __unicode__(self): return u'%s' % self.nome

class Usuario(ModelDefault):
    class Meta:
        verbose_name = _(u'Cliente')
        verbose_name_plural = _(u'Clientes')
        ordering = ['nome']

    operadora           = models.ForeignKey(Operadora, verbose_name=_(u'Operadora'), blank=True, null=True,)
    bairro              = models.ForeignKey(Bairro, verbose_name=_(u'Bairro'), blank=True, null=True,)
    categoria           = models.ForeignKey(Categoria, verbose_name=_(u'Categoria'),)
    nome                = models.CharField(verbose_name=_(u'Nome'), max_length=150, blank=True, null=True,)
    data_nascimento     = models.DateField(verbose_name=_(u'Data de Nascimento'), auto_now_add=False, blank=True, null=True)
    celular             = models.CharField(verbose_name=_(u'Celular'), max_length=15, unique=True)
    cep                 = models.CharField(verbose_name=_(u'CEP'), max_length=15, blank=True, null=True, help_text=mark_safe('<a class="lbuscacep" target="_blank" href="http://www.buscacep.correios.com.br/servicos/dnec/menuAction.do?Metodo=menuEndereco">Não sabe o CEP? Consulte aqui!</a>'))
    notificacoes        = models.BooleanField(verbose_name=_(u'Receber Mensagens SMS/Voz?'), default=True, blank=True, editable=False)
    origem              = models.CharField(u"Origem", max_length=1, default=ORIGEM_FORMULARIO, choices=ORIGEM_CHOICES,)
    numero_invalido     = models.BooleanField(verbose_name=_(u'Número Inválido?'), default=False, blank=True, )

    def __unicode__(self):
        if not self.nome: return u"Cliente 00%s" % self.pk
        return u'%s' % (self.nome)

    def celular_tostr(self):

        if len(self.celular) >= 11: return '(%s) %s - %s' %(self.celular[0:2], self.celular[2:7], self.celular[7:11])
        return '(%s) %s - %s' %(self.celular[0:2], self.celular[2:6], self.celular[6:11])

def celular_to_int(numero):

    celular = re.sub('[()-]', '', numero)
    celular = celular.replace(" ", "")

    if int(celular[:1]) == 0:
        celular = celular[1:]

    if len(celular) < 9:
        return False

    if len(celular) > 11:
        return False

    ddds = range(11,99)
    ddd = int(celular[:2])

    if not ddd in ddds:
        return False

    return celular

def importa_arquivo_csv(arquivo, categoria):
    with open(arquivo, 'r') as f:
        reader = csv.reader(f)
        total_importacoes = 0

        for row in reader:

            celular, cep, nome = "", "", ""

            try: cep = row[1]
            except IndexError: pass

            try:nome = row[2]
            except IndexError:pass

            try:
                celular = celular_to_int(row[0])
                if not Usuario.objects.filter(celular=celular).exists() and celular:
                    Usuario(celular=celular, cep=cep, nome=nome, categoria_id=categoria).save()
                    total_importacoes = total_importacoes + 1
            except: pass

    if os.path.exists(arquivo):os.remove(arquivo)
    return total_importacoes

front/models.py
# -*- coding: utf-8 -*-

front/forms.py
# -*- coding: utf-8 -*-

front/views.py
# coding=utf-8
from django.shortcuts import render
from cadastro.models import Usuario, Bairro, Categoria, ORIGEM_CHOICES
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from libs.util import list_paginator
from mensagem.models import Mensagem, MensagemPadrao, StatusMensagem
from conteudo.models import CodigoPromocional, New
from mensagem.api import consulta_status_detalhado
from front.decorators import verifica_termos_uso

@login_required(login_url='/login/')
@verifica_termos_uso()
def index(request):

    # print consulta_status_detalhado('')

    kwargs = {}
    args = []

    categoria       = request.GET.get('categoria', False)
    bairro          = request.GET.get('bairro', False)
    nome            = request.GET.get('nome_celular', False)
    mensagem_padrao = request.GET.get('mensagem_padrao', False)
    status          = request.GET.get('status', False)
    codigo          = request.GET.get('codigo', False)
    noticia         = request.GET.get('noticia', False)
    id_usuario         = request.GET.get('id_usuario', False)

    if categoria: kwargs['categoria'] = categoria
    if codigo: kwargs['codigo_promocional'] = codigo
    if id_usuario: kwargs['usuario'] = id_usuario

    if bairro: kwargs['bairro'] = bairro
    if mensagem_padrao: kwargs['mensagem_padrao'] = mensagem_padrao
    if status: kwargs['status'] = status
    if noticia: kwargs['noticia'] = noticia

    if nome: args = [Q(texto__icontains=nome) | Q(usuario__nome__contains=nome) | Q(usuario__celular__contains=nome)]

    opts_filtros = [200, 999, 5000, 5001, 5002, 000, 10, 13, 100, 110, 111, 120, 133, 134, 150, 160, 161, 171, 190, 01]

    mensagens = Mensagem.objects.filter(*args, **kwargs)

    for mensagem in mensagens:
        mensagem.atualiza_status()

    dados = {
        'titulo': u'SMS - (%s) ' % Mensagem.objects.filter(*args, **kwargs).count(),
        'mensagens': list_paginator(request, mensagens, 20),
        'bairros': Bairro.objects.all(),
        'categorias': Categoria.objects.all(),
        'mensagens_padrao': MensagemPadrao.objects.all(),
        'noticias': New.objects.all(),
        'codigo_promocionais': CodigoPromocional.objects.all(),
        'status': StatusMensagem.objects.filter(codigo__in=opts_filtros),
        'origens': dict(ORIGEM_CHOICES),
        'menu': "menu_mensagens",
    }

    return render(request, 'mensagens/mensagens.html', dados)

@login_required(login_url='/login/')
def msg_padrao(request):
    return render(request, 'mensagens-padrao/mensagens-padrao.html', {'titulo': u'SMS Padrão', 'menu': "menu_mensagem", 'mensagens': list_paginator(request, MensagemPadrao.objects.all(), 50),})

@login_required(login_url='/login/')
def noticias(request):
    return render(request, 'noticias/noticias.html', {'titulo': u'Noticias', 'menu': "menu_conteudo", 'noticias': list_paginator(request, New.objects.all(), 50),})

@login_required(login_url='/login/')
def codigos_promocionais(request):

    kwargs = {}
    args = []

    codigo = request.GET.get('codigo', False)
    if codigo:args = [Q(codigo__icontains=request.GET.get('codigo', False))]

    dados = {
        'titulo': u'Códigos Promocionais',
        'menu': "menu_conteudo",
        'codigos': list_paginator(request, CodigoPromocional.objects.filter(*args, **kwargs), 100),
    }

    return render(request, 'codigos/codigos.html', dados)

@login_required(login_url='/login/')
def clientes(request):

    kwargs = {}
    args = []

    categoria = request.GET.get('categoria', False)
    bairro = request.GET.get('bairro', False)
    nome = request.GET.get('nome_celular', False)
    origem = request.GET.get('origem', False)

    if categoria: kwargs['categoria'] = categoria
    if bairro: kwargs['bairro'] = bairro
    if origem: kwargs['origem'] = origem
    
    if nome: args = [Q(nome__icontains=nome) | Q(celular__contains=nome)]

    dados = {
        'titulo': u'Clientes (%s)' % Usuario.objects.all().count(),
        'clientes': list_paginator(request, Usuario.objects.filter(*args, **kwargs).filter(numero_invalido=False), 50),
        'bairros': Bairro.objects.all(),
        'categorias': Categoria.objects.all(),
        'origens': dict(ORIGEM_CHOICES),
        'menu': "menu_clientes",
    }

    return render(request, 'clientes/clientes.html', dados)

@login_required(login_url='/login/')
def categorias(request):
    return render(request, 'categorias/categorias.html', {'titulo': u'Categorias', 'categorias': Categoria.objects.all(), 'menu': "menu_clientes",})

@login_required(login_url='/login/')
def bairros(request):
    return render(request, 'bairros/bairros.html',{'titulo': u'Bairros', 'bairros': Bairro.objects.all(), 'menu': "menu_clientes",})

front/templates/clientes/cancelar_assinatura_confirmacao.html
{% extends "front.html" %}
{% load front_extras %}
{% load widget_tweaks %}
{% load thumbnail %}

{% block menu_left %}

    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element">
                    <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold"
                                                                             style="color: #fff;">{{ configuracao.nome }}</strong></span>
                    </div>
                    <div class="logo-element">
                        Keep
                    </div>
                </li>

            </ul>

        </div>
    </nav>

{% endblock %}

{% block bar_top %}{% endblock %}
{% block info_creditos %}{% endblock %}
{% block zopin %}{% endblock %}
{% block content %}

    <div class="row">

        <div class="wrapper wrapper-content animated fadeInUp">
            <div class="ibox">
                <div class="ibox-content">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                        {% endfor %}
                    {% endif %}

                </div>
            </div>
        </div>

    </div>

{% endblock %}

front/templates/clientes/clientes.html
{% extends "front.html" %}
{% load front_extras %}
{% load bootstrap_pagination %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
                <div class="ibox-content">

                    <div class="text-right">
                         <a href="{% url "cadastro:novo" %}" class="btn btn-success"> Adicionar Cliente </a>
                    </div>

                    <form action="{% url "front:clientes" %}">
                        <div class="row">
                            <div class="col-sm-2 m-b-xs">
                                <select name="bairro" class="input-sm form-control input-s-sm inline">
                                    <option value="">Filtrar por Bairro</option>
                                    {% for bairro in bairros %}
                                        <option value="{{ bairro.pk }}"
                                                {% ifequal bairro.pk|add:"0" request.GET.bairro|add:"0" %}
                                                selected="selected" {% endifequal %}>{{ bairro.nome }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="col-sm-3 m-b-xs">
                                <select name="categoria" class="input-sm form-control input-s-sm inline">
                                    <option value="">Filtrar por Categoria</option>
                                    {% for categoria in categorias %}
                                        <option value="{{ categoria.pk }}"
                                                {% ifequal categoria.pk|add:"0" request.GET.categoria|add:"0" %}
                                                selected="selected" {% endifequal %}>{{ categoria.nome }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="col-sm-2 m-b-xs">
                                <select name="origem" class="input-sm form-control input-s-sm inline">
                                    <option value="">Origem</option>
                                    {% for key,value in origens.items %}
                                        <option value="{{ key }}"
                                                {% ifequal key|add:"0" request.GET.origem|add:"0" %}
                                                selected="selected" {% endifequal %}>{{ value }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="col-sm-3">
                                <div class="input-group">
                                    <input name="nome_celular" type="text" placeholder="Digite nome ou celular"
                                           class="input-sm form-control">
                                    <span class="input-group-btn"><button type="submit" class="btn btn-sm btn-primary">
                                        Filtrar
                                    </button> </span>
                                </div>
                            </div>
                        </div>
                    </form>

                    <div class="table-responsive margem_table_lista">

                        {% if not clientes %}

                            <div class="alert alert-warning alert-dismissable">
                                <i class="fa fa-warning"></i> Sua busca não encontrou nenhum resultado.
                            </div>

                        {% endif %}

                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Celular</th>
                                <th>Bairro</th>
                                <th>Receber SMS Marketing? <i data-toggle="tooltip" data-placement="top" class="fa fa-info-circle text-navy" title="Usuários que permitiram recebimento de campanhas"></i></th>
                                <th>Origem</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for cliente in clientes %}
                                <tr>
                                    <td><a href="{% url "cadastro:detalhes" cliente.pk %}" title="Clique para editar">{{ cliente }}</a></td>
                                    <td>{{ cliente.celular_tostr }}</td>

                                    <td>{{ cliente.bairro|default:"--" }}</td>
                                    <td>
                                        {% if cliente.notificacoes %}
                                            <i class="fa fa-check-square text-navy"> Sim</i>
                                        {% else %}
                                            <span class="label label-warning">Não </span>
                                        {% endif %}

                                    </td>
                                    <td>{{ cliente.get_origem_display }}</td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                        {% bootstrap_paginate clientes previous_label="Anterior" next_label="Seguinte" %}
                    </div>

                </div>
            </div>
        </div>

    </div>

{% endblock %}

front/templates/clientes/editar.html
{% extends "front.html" %}
{% load front_extras %}
{% load widget_tweaks %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">

                <div class="ibox-content">

                    <div class="panel-body col-lg-6">
                        <div class="pull-right">
                            <a href="{% url "front:clientes" %}" class="label"> <span class="fa fa-bars fa-1x"> </span> Voltar para lista </a>
                        </div>
                        <form action="{% url "cadastro:editar" usuario.pk %}" method="post" role="form">
                            {% csrf_token %}
                            <input type="hidden" name="bairro" id="id_bairro" value="{{ usuario.bairro.pk }}"/>
                            <input type="hidden" name="origem" value="{{ usuario.origem }}"/>

                            <div class="form-group">

                                <label>Celular:</label>
                                {{ form.celular.errors }}
                                {{ form.celular|add_class:"form-control"|attr:"required:true" }}
                            </div>

                            <div class="form-group">

                                <label>Categoria:</label>
                                {{ form.categoria.errors }}
                                {{ form.categoria|add_class:"form-control"|attr:"required:true" }}
                            </div>

                            <div class="form-group">

                                <label>Nome:</label>
                                {{ form.nome.errors }}
                                {{ form.nome|add_class:"form-control" }}
                            </div>

                            <div class="form-group">

                                <label>CEP:</label>
                                {{ form.cep.errors }}
                                {{ form.cep|add_class:"form-control" }}
                                <a class="lbuscacep"
                                   href="http://www.buscacep.correios.com.br/servicos/dnec/menuAction.do?Metodo=menuEndereco"
                                   target="_blank">Não sabe o CEP? Consulte aqui!</a>
                            </div>

                            <div class="form-group" id="data_1">
                                <label>Data de Nascimento:</label>

                                <div class="input-group date">
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    {{ form.data_nascimento.errors }}
                                    {{ form.data_nascimento|add_class:"form-control" }}
                                </div>
                            </div>

                            <div class="form-group">
                                <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"
                                        name="salvar" value="1" style="margin-left: 15px">
                                    <strong>Salvar</strong></button>

                            </div>

                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

front/templates/clientes/invalidos.html
{% extends "front.html" %}
{% load front_extras %}
{% load bootstrap_pagination %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
                <div class="ibox-content">

                    {% if clientes %}
                        <div class="text-right">
                            <button type="button" data-toggle="modal" data-target="#confirmar_remocao" class="btn btn-danger"><strong> Remover números inválidos</strong></button>
                        </div>
                    {% endif %}

                     {% if clientes %}
                         <div class="alert alert-warning alert-dismissable">
                            Números inválidos são números reprovados pelas operadoras. <a href="#" target="_blank"> Veja como funciona. </a>
                         </div>
                    {% endif %}

                    <div class="table-responsive margem_table_lista">

                        {% if not clientes %}

                            <div class="alert alert-warning alert-dismissable">
                                Nenhum número inválido foi encontrado.
                            </div>

                        {% endif %}

                         {% if clientes %}

                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Celular</th>
                                    <th>Bairro</th>
                                    <th>Origem</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for cliente in clientes %}
                                    <tr>
                                        <td><a href="{% url "cadastro:detalhes" cliente.pk %}"
                                               title="Clique para editar">{{ cliente }}</a></td>
                                        <td>{{ cliente.celular_tostr }}</td>
                                        <td>{{ cliente.bairro|default:"--" }}</td>
                                        <td>{{ cliente.get_origem_display }}</td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                            {% bootstrap_paginate clientes previous_label="Anterior" next_label="Seguinte" %}

                        {% endif %}

                    </div>

                </div>
            </div>
        </div>

    </div>

    <form id="form_remover_numeros_invalidos" method="post" action="{% url "cadastro:remover_numeros_invalidos" %}">
        {% csrf_token %}
    </form>

    <div class="modal inmodal" id="confirmar_remocao" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated bounceInRight">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <i class="fa fa-envelope modal-icon"></i>
                    <h4 class="modal-title">Confirme a remoção</h4>

                </div>
                <div class="modal-body">
                    <p>Tem certeza?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-dismiss="modal">Fechar</button>
                    <button type="button" class="btn btn-primary" id="btn_confirmar_remocao">Sim, remover</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

front/templates/clientes/novo.html
{% extends "front.html" %}
{% load front_extras %}
{% load widget_tweaks %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">

                <div class="ibox-content">

                    <div class="panel-body col-lg-6">

                        <div class="pull-right">
                            <a href="{% url "front:clientes" %}" class="label"> <span class="fa fa-bars fa-1x"> </span> Voltar para lista </a>
                        </div>

                        {% if form.non_field_errors %}
                            <div class="alert alert-danger">{{ form.non_field_errors }}</div>
                        {% endif %}

                        <form action="{% url "cadastro:novo" %}" method="post" role="form">
                            {% csrf_token %}
                            <input type="hidden" name="bairro" id="id_bairro"/>
                            <input type="hidden" name="origem" value="f"/>


                            <div class="form-group">

                                <label>Celular:</label> <span class="marca_texto_vermelho">(Obrigatório)</span>
                                {{ form.celular.errors }}
                                {{ form.celular|add_class:"form-control"|attr:"required:true"|attr:"type:tel" }}
                            </div>

                            <div class="form-group">

                                <label>Categoria:</label> <span class="marca_texto_vermelho">(Obrigatório)</span>
                                {{ form.categoria.errors }}
                                {{ form.categoria|add_class:"form-control"|attr:"required:true" }}
                            </div>

                            <div class="form-group">

                                <label>Nome:</label>
                                {{ form.nome.errors }}
                                {{ form.nome|add_class:"form-control" }}
                            </div>

                            <div class="form-group">

                                <label>CEP:</label>
                                {{ form.cep.errors }}
                                {{ form.cep|add_class:"form-control" }}
                                <a class="lbuscacep"
                                   href="http://www.buscacep.correios.com.br/servicos/dnec/menuAction.do?Metodo=menuEndereco"
                                   target="_blank">Não sabe o CEP? Consulte aqui!</a>
                            </div>

                            <div class="form-group" id="data_1">
                                <label>Data de Nascimento:</label>

                                <div class="input-group date">
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    {{ form.data_nascimento.errors }}
                                    {{ form.data_nascimento|add_class:"form-control" }}
                                </div>
                            </div>

                            <div class="form-group">
                                <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"
                                        name="salvar" value="1" style="margin-left: 15px"><strong>Salvar</strong>
                                </button>
                                <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"
                                        name="salvar" value="2"><strong>Salvar e adicionar outro</strong></button>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>

{% endblock %}