autenticacao/urls.py
# coding=utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('autenticacao.views',

                       url(r'^sair/$', 'sair', name='sair'),
                       url(r'^login/$', 'entrar', name='login'),
                       url(r'^configuracoes/$', 'configuracoes', name='configuracoes'),
                       url(r'^termos-de-uso/$', 'termos', name='termos'),
                       url(r'^editar-senha/$', 'editar_senha', name='editar_senha'),
                       url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'restaurar_senha', name='password_reset_confirm'),
                       url(r'^reset/$', 'reset', name='reset'),

)

cadastro/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
urlpatterns = patterns('cadastro.views',
        url(r'^detalhe-cliente/(?P<id>\d+)$', 'detalhes', name='detalhes'),
        url(r'^desabilitar-recebimento-campanha/(?P<id>\d+)$', 'desabilitar_recebimento_campanha', name='desabilitar_recebimento_campanha'),
        url(r'^editar-cliente/(?P<id>\d+)$', 'editar', name='editar'),
        url(r'^novo-cliente/$', 'novo', name='novo'),
        url(r'^importar-planilha/$', 'importar_planilha', name='importar_planilha'),
        url(r'^editar-categoria/(?P<id>\d+)$', 'editar_categoria', name='editar_categoria'),
        url(r'^novo-categoria/$', 'nova_categoria', name='nova_categoria'),
        url(r'^cancelar-categoria/(?P<id>\d+)$', 'cancelar_categoria', name='cancelar_categoria'),
        url(r'^numeros-invalidos/$', 'numeros_invalidos', name='numeros_invalidos'),
        url(r'^remover-numeros-invalidos/$', 'remover_numeros_invalidos', name='remover_numeros_invalidos'),
)

financeiro/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
urlpatterns = patterns('financeiro.views',
    url(r'^nova-recarga/$', 'recarga', name='recarga'),
    url(r'^recargas/$', 'recargas', name='recargas'),
    url(r'^tarifador/$', 'tarifador', name='tarifador'),
    url(r'^pagamento/sucesso/$', 'sucesso', name='sucesso'),
    url(r'^atualiza-credito/$', 'atualiza_credito', name='atualiza_credito'),
    url(r'^pagamento/$', 'pagamento', name='pagamento'),
    url(r'^cria-recarga-cliente/$', 'criar_recarga_retorno', name='criar_recarga_retorno'),

)

front/urls.py
# coding=utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('front.views',
                       url(r'^$', 'index', name='index'),
                       url(r'^clientes/$', 'clientes', name='clientes'),
                       url(r'^categorias/$', 'categorias', name='categorias'),
                       url(r'^bairros/$', 'bairros', name='bairros'),
                       url(r'^codigos-promocionais/$', 'codigos_promocionais', name='codigos_promocionais'),
                       url(r'^noticias/$', 'noticias', name='noticias'),
                       url(r'^msg-padrao/$', 'msg_padrao', name='msg_padrao'),

)

keepsms/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

                       url(r'^gestao/', include(admin.site.urls)),
                       url('', include('cadastro.urls', namespace='cadastro')),
                       url('', include('localizacao.urls', namespace='localizacao')),
                       url('', include('front.urls', namespace='front')),
                       url('', include('mensagem.urls', namespace='mensagem')),
                       url('', include('conteudo.urls', namespace='conteudo')),
                       url('', include('financeiro.urls', namespace='financeiro')),
                       url('', include('autenticacao.urls', namespace='autenticacao')),
                       url(r'^retorno/pagseguro/', include('pagseguro.urls')),

)

if settings.DEBUG:
    urlpatterns = patterns('',
                           url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                               {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                           url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
                               {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
    ) + urlpatterns

mensagem/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
urlpatterns = patterns('mensagem.views',

        url(r'^enviar-mensagem/$', 'nova_mensagem', name='nova_mensagem'),
        url(r'^enviar-mensagem-selecao/$', 'nova_mensagem_selecao', name='nova_mensagem_selecao'),
        url(r'^enviar-codigo-promocional/$', 'nova_mensagem_codigo_promocional', name='nova_mensagem_codigo_promocional'),
        url(r'^enviar-noticia/$', 'nova_mensagem_noticia', name='nova_mensagem_noticia'),
        url(r'^cancelar-agendamento/(?P<id>\d+)$', 'cancelar_agendamento', name='cancelar_agendamento'),
        url(r'^massa/$', 'massa', name='massa'),
        url(r'^fila/$', 'fila', name='fila'),
        url(r'^d/$', 'detalhe_mensagem', name='detalhe_mensagem'),
        url(r'^exemplos/$', 'exemplos', name='exemplos'),
        url(r'^diferenca/$', 'diferenca', name='diferenca'),
        url(r'^link-confirmacao/$', 'link_confirmacao', name='link_confirmacao'),
        url(r'^faq/$', 'faq', name='faq'),
        url(r'^recebidas/$', 'mensagens_recebidas', name='mensagens_recebidas'),
        url(r'^mensagem-teste/$', 'mensagem_teste', name='mensagem_teste'),
        url(r'^nova-msg-padrao/$', 'nova_msg_padrao', name='nova_msg_padrao'),
        url(r'^editar-msg-padrao/(?P<id>\d+)$', 'editar_msg_padrao', name='editar_msg_padrao'),
)

front/models.py
# -*- coding: utf-8 -*-

front/forms.py
# -*- coding: utf-8 -*-

front/views.py
# coding=utf-8
from django.shortcuts import render
from cadastro.models import Usuario, Bairro, Categoria, ORIGEM_CHOICES
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from libs.util import list_paginator
from mensagem.models import Mensagem, MensagemPadrao, StatusMensagem
from conteudo.models import CodigoPromocional, New
from mensagem.api import consulta_status_detalhado
from front.decorators import verifica_termos_uso

@login_required(login_url='/login/')
@verifica_termos_uso()
def index(request):

    # print consulta_status_detalhado('')

    kwargs = {}
    args = []

    categoria       = request.GET.get('categoria', False)
    bairro          = request.GET.get('bairro', False)
    nome            = request.GET.get('nome_celular', False)
    mensagem_padrao = request.GET.get('mensagem_padrao', False)
    status          = request.GET.get('status', False)
    codigo          = request.GET.get('codigo', False)
    noticia         = request.GET.get('noticia', False)
    id_usuario         = request.GET.get('id_usuario', False)

    if categoria: kwargs['categoria'] = categoria
    if codigo: kwargs['codigo_promocional'] = codigo
    if id_usuario: kwargs['usuario'] = id_usuario

    if bairro: kwargs['bairro'] = bairro
    if mensagem_padrao: kwargs['mensagem_padrao'] = mensagem_padrao
    if status: kwargs['status'] = status
    if noticia: kwargs['noticia'] = noticia

    if nome: args = [Q(texto__icontains=nome) | Q(usuario__nome__contains=nome) | Q(usuario__celular__contains=nome)]

    opts_filtros = [200, 999, 5000, 5001, 5002, 000, 10, 13, 100, 110, 111, 120, 133, 134, 150, 160, 161, 171, 190, 01]

    mensagens = Mensagem.objects.filter(*args, **kwargs)

    for mensagem in mensagens:
        mensagem.atualiza_status()

    dados = {
        'titulo': u'SMS - (%s) ' % Mensagem.objects.filter(*args, **kwargs).count(),
        'mensagens': list_paginator(request, mensagens, 20),
        'bairros': Bairro.objects.all(),
        'categorias': Categoria.objects.all(),
        'mensagens_padrao': MensagemPadrao.objects.all(),
        'noticias': New.objects.all(),
        'codigo_promocionais': CodigoPromocional.objects.all(),
        'status': StatusMensagem.objects.filter(codigo__in=opts_filtros),
        'origens': dict(ORIGEM_CHOICES),
        'menu': "menu_mensagens",
    }

    return render(request, 'mensagens/mensagens.html', dados)

@login_required(login_url='/login/')
def msg_padrao(request):
    return render(request, 'mensagens-padrao/mensagens-padrao.html', {'titulo': u'SMS Padrão', 'menu': "menu_mensagem", 'mensagens': list_paginator(request, MensagemPadrao.objects.all(), 50),})

@login_required(login_url='/login/')
def noticias(request):
    return render(request, 'noticias/noticias.html', {'titulo': u'Noticias', 'menu': "menu_conteudo", 'noticias': list_paginator(request, New.objects.all(), 50),})

@login_required(login_url='/login/')
def codigos_promocionais(request):

    kwargs = {}
    args = []

    codigo = request.GET.get('codigo', False)
    if codigo:args = [Q(codigo__icontains=request.GET.get('codigo', False))]

    dados = {
        'titulo': u'Códigos Promocionais',
        'menu': "menu_conteudo",
        'codigos': list_paginator(request, CodigoPromocional.objects.filter(*args, **kwargs), 100),
    }

    return render(request, 'codigos/codigos.html', dados)

@login_required(login_url='/login/')
def clientes(request):

    kwargs = {}
    args = []

    categoria = request.GET.get('categoria', False)
    bairro = request.GET.get('bairro', False)
    nome = request.GET.get('nome_celular', False)
    origem = request.GET.get('origem', False)

    if categoria: kwargs['categoria'] = categoria
    if bairro: kwargs['bairro'] = bairro
    if origem: kwargs['origem'] = origem
    
    if nome: args = [Q(nome__icontains=nome) | Q(celular__contains=nome)]

    dados = {
        'titulo': u'Clientes (%s)' % Usuario.objects.all().count(),
        'clientes': list_paginator(request, Usuario.objects.filter(*args, **kwargs).filter(numero_invalido=False), 50),
        'bairros': Bairro.objects.all(),
        'categorias': Categoria.objects.all(),
        'origens': dict(ORIGEM_CHOICES),
        'menu': "menu_clientes",
    }

    return render(request, 'clientes/clientes.html', dados)

@login_required(login_url='/login/')
def categorias(request):
    return render(request, 'categorias/categorias.html', {'titulo': u'Categorias', 'categorias': Categoria.objects.all(), 'menu': "menu_clientes",})

@login_required(login_url='/login/')
def bairros(request):
    return render(request, 'bairros/bairros.html',{'titulo': u'Bairros', 'bairros': Bairro.objects.all(), 'menu': "menu_clientes",})

front/templates/front.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{{ configuracao.nome }}</title>

    {% block meta_tags %}

    {% endblock %}

    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="{{ STATIC_URL }}css/animate.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/custom.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}js/plugins/jquery-ui/jquery-ui.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/plugins/datapicker/datepicker3.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/plugins/switchery/switchery.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/plugins/chosen/chosen.css" rel="stylesheet">

    <script src="{{ STATIC_URL }}js/jquery-2.1.1.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/plugins/jquery-ui/jquery-ui.min.js"></script>

    <script src="{{ STATIC_URL }}js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="{{ STATIC_URL }}js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    {% block zopin %}
        {% if not is_mobile %}
            <!--Start of Zopim Live Chat Script-->
            <script type="text/javascript">
            window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
            d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
            _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
            $.src="//v2.zopim.com/?LyrsyrXFXvuAJ9D8tBkrt2d74GlRqrml";z.t=+new Date;$.
            type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
            </script>
            <!--End of Zopim Live Chat Script-->
        {% endif %}
    {% endblock %}
</head>

<body>

<div id="wrapper">

    {% block menu_left %}
        {% include "menu_left.html" %}
    {% endblock %}

    <div id="page-wrapper" class="gray-bg">

        <!-- Tool bar rop -->

    {% block bar_top %}
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <span minimaliza-sidebar></span>
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                </div>
                <ul class="nav navbar-top-links navbar-right">

                    <li>
                        <span class="m-r-sm text-muted welcome-message">Keep SMS|| contato@site.com || (34) 00-00</span>
                    </li>

                    <li>
                        <a href="{% url "autenticacao:sair" %}">
                            <i class="fa fa-sign-out"></i> Sair
                        </a>
                    </li>

                </ul>

            </nav>
        </div>
    {% endblock %}

        <div class=" animated fadeInRight">
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-12">
                    {% block info_creditos %}

                        {% if not is_mobile %}
                            <div class="pull-right">
                                    <span class="label label-danger"> <span class="fa fa-envelope-o fa-1x"> </span> Créditos: R$ {{ total_credito }} || Valor SMS {{ valor_sms }} </span>
                                    <span style="margin-left: 5px" class="label label-info"> <span class="fa fa-group fa-1x"> </span> Restam: {{ pode_atingir }} SMS </span>
                                    <span style="margin-left: 5px" class="label label-info"> <span class="fa fa-info fa-1x"> </span> Seu ID: 00{{ codigo }}  </span>
                            </div>
                        {% endif %}
                    {% endblock %}

                    <h2>{{ titulo }}</h2>
                </div>

            <div class="row" style="clear: both; margin: 0 14px">
                {% if not saldo_positivo %}
                    <div class="alert alert-danger">
                        Seus créditos esgotaram, faça uma <a href="{% url "financeiro:recarga" %}"> recarga </a> e alcance sua próxima meta.
                        <a href="{% url "financeiro:recarga" %}"> <span class="fa fa-repeat fa-1x"> </span> Recarregar </a>
                    </div>
                {% endif %}

                {% block configuracao_assinatura_sms %}

                    {% if not configuracao.assinatura_sms %}
                        <div class="alert alert-danger">
                            Configure a assinatura do seu SMS:
                            <a href="{% url "autenticacao:configuracoes" %}"> <span class="fa fa-cogs fa-1x"> </span> Configurar </a>
                        </div>
                    {% endif %}

               {% endblock %}

            <div style="padding: 0 0 20px 0">
                {% block content %}{% endblock %}
            </div>
        </div>

        {% block rodape %}
{#            <div class="footer" style="clear: both">#}
{#                <div class="pull-right">#}
{#                    <a href="http://site.com"><strong>Keep SMS</strong></a>#}
{#                </div>#}
{#                <div>#}
{#                    <strong>Copyright</strong> Keep Sistemas &copy; 2014-2015#}
{#                </div>#}
{#            </div>#}
        {% endblock %}

    </div>

</div>

<script src="{{ STATIC_URL }}js/inspinia.js"></script>
<script src="{{ STATIC_URL }}js/plugins/datapicker/bootstrap-datepicker.js"></script>
<script src="{{ STATIC_URL }}js/plugins/pace/pace.min.js"></script>
<script src="{{ STATIC_URL }}js/plugins/iCheck/icheck.min.js"></script>
<script src="{{ STATIC_URL }}js/jquery.mask.min.js"></script>
<script src="{{ STATIC_URL }}js/plugins/switchery/switchery.js"></script>
<script src="{{ STATIC_URL }}js/jquery.word-and-character-counter.min.js"></script>
<script src="{{ STATIC_URL }}js/plugins/chosen/chosen.jquery.js"></script>
<script src="{{ STATIC_URL }}js/jquery.magnific-popup.min.js"></script>
<script src="{{ STATIC_URL }}js/custom.js"></script>
<script>
    $("#{{ menu }}").addClass('active');
</script>

</body>

</html>

front/templates/menu_left.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">

            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong
                                    class="font-bold">{{ configuracao.nome }}</strong>
                             </span> <span class="text-muted text-xs block">{{ configuracao.responsavel }} <b
                                    class="caret"></b></span> </span> </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="{% url "autenticacao:sair" %}">Sair</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    Keep
                </div>
            </li>

            {% if configuracao.aceitou_termos %}
                <li id="menu_mensagens">
                    <a href="#"><i class="fa fa-envelope"></i> <span class="nav-label">SMS</span><span
                            class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse out" aria-expanded="false">
                        <li><a href="{% url "front:index" %}">Lista de SMS</a></li>
                        <li><a href="{% url "mensagem:exemplos" %}">Exemplos de SMS</a></li>
                        <li><a href="{% url "front:msg_padrao" %}">SMS Padrão</a></li>
                        <li><a href="{% url "financeiro:tarifador" %}">Tarifador</a></li>
                        {% if not saldo_positivo %}
                            <li><a href="{% url "financeiro:recargas" %}">Recarga</a></li>
                        {% endif %}
                    </ul>
                </li>

                <li id="menu_clientes">
                    <a href="#"><i class="fa fa-user"></i> <span class="nav-label">Meus Clientes</span><span
                            class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse out" aria-expanded="false">
                        <li><a href="{% url "front:clientes" %}">Lista de Clientes</a></li>
                        <li><a href="{% url "front:bairros" %}">Bairros</a></li>
                        <li><a href="{% url "front:categorias" %}">Categorias</a></li>
                        <li><a href="{% url "cadastro:numeros_invalidos" %}">Números Inválidos</a></li>
                        <li><a href="{% url "cadastro:importar_planilha" %}">Importar Planilha</a></li>
                    </ul>
                </li>

                <li id="menu_conteudo">
                <a href="#"><i class="fa fa-share-alt-square"></i> <span class="nav-label">Conteúdo</span><span
                        class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse out" aria-expanded="false">
                    <li><a href="{% url "front:noticias" %}">Notícias</a></li>
                    <li><a href="{% url "front:codigos_promocionais" %}">Códigos promocionais</a></li>
                </ul>
            </li>
            {% endif %}
            <li id="menu_config">
                <a href="{% url "autenticacao:configuracoes" %}"><i class="fa fa-cogs"></i> <span class="nav-label">Configurações</span><span
                        class="fa arrow"></span></a>
            </li>

            <li id="menu_faq">
                <a href="{% url "mensagem:faq" %}"><i class="fa fa-comments"></i> <span class="nav-label">Perguntas Frequentes</span><span
                        class="fa arrow"></span></a>
            </li>
            <li id="menu_config">
                <a href="{% url "autenticacao:termos" %}"><i class="fa fa-info"></i> <span class="nav-label">Termos de Uso</span><span
                        class="fa arrow"></span></a>
            </li>


        </ul>

    </div>
</nav>